In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
arr
    

array([1, 2, 3, 4])

In [3]:
reshaped=arr.reshape(2,2)
reshaped

array([[1, 2],
       [3, 4]])

In [4]:
flattened=reshaped.flatten()
flattened

array([1, 2, 3, 4])

In [5]:
flattened=reshaped.flatten()
flattened[0]=36
flattened

array([36,  2,  3,  4])

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
raveled=reshaped.ravel()
raveled[1]=88
raveled

array([ 1, 88,  3,  4])

In [8]:
arr

array([ 1, 88,  3,  4])

In [9]:
reshaped

array([[ 1, 88],
       [ 3,  4]])

In [10]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([1,2,3])
print(arr2)

[1 2 3]
[1 2 3]


In [11]:
arr1+arr2

array([2, 4, 6])

In [12]:
arr1+arr2

array([2, 4, 6])