In [2]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.7 MB 2.6 MB/s eta 0:00:04
   ------ --------------------------------- 1.3/8.7 MB 2.3 MB/s eta 0:00:04
   -------- ------------------------------- 1.8/8.7 MB 2.5 MB/s eta 0:00:03
   ------------ --------------------------- 2.6/8.7 MB 2.9 MB/s eta 0:00:03
   -------------- ------------------------- 3.1/8.7 MB 2.9 MB/s eta 0:00:02
   ---------------- ----------------------- 3.7/8.7 MB 2.7 MB/s eta 0:00:02
   ------------------- -------------------- 4.2/8.7 MB 2.7 MB/s eta 0:00:02
   -------------------- ------------------- 4.5/8.7 MB 2.6 MB/s eta 0:00:02
   ---------------------- ----------------- 5.0/8.7 MB 2.5 MB/s eta 0:00:02
   ------------------------- -------------- 5.5/8.7 MB 2.5 MB/s eta 0:00:02
   ---------------------

In [4]:
from sklearn.pipeline import Pipeline

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


In [8]:
steps = [("standard_scaler",StandardScaler()),("classifier",LogisticRegression())]

In [9]:
steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [10]:
pipe=Pipeline(steps)

In [11]:
from sklearn import set_config

In [13]:
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [14]:
from sklearn.datasets import make_classification

In [15]:
X,y=make_classification(n_samples=1000)

In [16]:
X.shape

(1000, 20)

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.33, random_state=42)
    


In [22]:
X_train

array([[-0.26139072,  1.57752001,  1.02019642, ...,  0.51615157,
        -0.85870522,  0.55684657],
       [ 0.26232398, -0.82180607,  0.37137669, ..., -0.41255412,
         0.36986066,  0.61202106],
       [-1.0856368 ,  0.03077212,  2.14549211, ...,  1.34516037,
         0.02675364,  0.35675625],
       ...,
       [-1.21943274,  0.97858176,  1.73643275, ...,  0.3458433 ,
         0.09799631,  0.75414251],
       [-0.91383211, -0.81407382, -1.14337158, ...,  0.31043083,
        -0.03855635,  0.47004832],
       [-0.85359242, -1.66796804,  0.58820961, ...,  0.69752459,
        -1.3164219 ,  1.31160239]], shape=(670, 20))

In [24]:
pipe.fit(X_train,y_train)
Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])
y_pred=pipe.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,

In [32]:
# Example 2
 #Displaying a pipeline with standard scaler, dimesnionality reduction and then estimato#
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [33]:
steps=[("scaling",StandardScaler()),
      ("PCA",PCA(n_components=3)),
      ("SVC",SVC())]
pipe2=Pipeline(steps)
pipe2.fit(X_train,y_train)
Pipeline(steps=[('scaling', StandardScaler()), ('PCA', 
PCA(n_components=3)),
                ('SVC', SVC())])
pipe2.predict(X_test)

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,

In [31]:
 from sklearn.impute import SimpleImputer

In [35]:
## numerical processing pipeline
import numpy as np
numeric_processor=Pipeline(
    
steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy
 ="mean")),
          ("scaler",StandardScaler())]
 )
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [37]:
##categorical procesing pipeline
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    
steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
          ("onehot",OneHotEncoder(handle_unknown="ignore"))]
 )
categorical_processor

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [38]:
## combine processing technqiues
from sklearn.compose import ColumnTransformer
preprocessor=ColumnTransformer(
    [("categorical",categorical_processor,["gender","City"]),
    ("numerical",numeric_processor,["age","height"])]
 )
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [39]:
 from sklearn.pipeline import make_pipeline
 pipe=make_pipeline(preprocessor,LogisticRegression())

In [40]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])